server:
  port: 8081

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${luyun.datasource.driver-class-name}
      url: jdbc:mysql://${luyun.datasource.host}:${luyun.datasource.port}/${luyun.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${luyun.datasource.username}
      password: ${luyun.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luyun.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      luyun:
        mapper: debug
        service: info
        controller: info

luyun:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: secert-key
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

mqtt:
  url: tcp://192.168.120.82:1887
  userName: smqtt
  password: smqtt
  clientId: myclient
  subTopics: rpub/rcu/objs/+
